---
# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format:check
      - name: Check linter
        run: npm run lint:check
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test -- --coverage
      - name: Upload test coverage to codecov
        uses: codecov/codecov-action@v4
        with:
          directory: coverage/
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ptitmouton/app-config

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - run: npm run build

  publish_to_npm:
    if: startsWith(github.ref, 'refs/tags')
    needs:
      - check
      - test
      - build
    permissions:
      contents: write
    uses: ./.github/workflows/__publish_to_npm.yaml
    secrets:
      npm-token: ${{ secrets.NPM_TOKEN }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}
